### ISSUE TITLE
δ and $ are not interchangeable in expression syntax

### ISSUE THREAD

**Issue by VikingScientist** [nutils/nutils#286]
If I run `examples/elasticity.py` with the sole change of swapping out the δ-symbol with a $-symbol, then I get the following exception

```
Traceback (most recent call last):
  File "/home/kjetijo/3rdPartyLibs/nutils/nutils/expression.py", line 516, in wrapper
    return f(self, *args, **kwargs)
  File "/home/kjetijo/3rdPartyLibs/nutils/nutils/expression.py", line 965, in tokenize
    raise _IntermediateError('Unknown symbol: {!r}.'.format(self.expression[pos]), at=pos)
nutils.expression._IntermediateError: Unknown symbol: '$'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kjetijo/3rdPartyLibs/nutils/nutils/cli.py", line 197, in call
    func(**kwargs)
  File "elasticity.py", line 29, in main
    ns.stress_ij = 'lmbda strain_kk $_ij + 2 mu strain_ij'
  File "/home/kjetijo/3rdPartyLibs/nutils/nutils/function.py", line 3566, in __setattr__
    ast, arg_shapes = expression.parse(value, variables=self._attributes, functions=self._functions_nargs, indices=indices, arg_shapes=self._arg_shapes, default_geometry_name=self.default_geometry_name)
  File "/home/kjetijo/3rdPartyLibs/nutils/nutils/expression.py", line 1193, in parse
    parser.tokenize()
  File "/home/kjetijo/3rdPartyLibs/nutils/nutils/expression.py", line 524, in wrapper
    raise ExpressionSyntaxError(e.msg + '\n' + self.expression + '\n' + ' '*at + '^'*count) from e
nutils.expression.ExpressionSyntaxError: Unknown symbol: '$'.
lmbda strain_kk $_ij + 2 mu strain_ij
                ^
```
```

**Comment by joostvanzwieten** [comment]
@VikingScientist: Can you confirm that #290 fixes this issue for you?

**Comment by VikingScientist** [comment]
This does seem to fix it for me, yes :+1:
