### ISSUE TITLE
Element.__str__ is broken

### ISSUE THREAD

**Issue by TheBB** [nutils/nutils#337]
domain, geom = mesh.rectilinear([[0, 1], [0, 1]])
    print(domain.elements[0])

    Traceback (most recent call last):
      File "/home/eivind/test.py", line 6, in <module>
        print(domain.elements[0])
      File "/home/eivind/repos/nutils/nutils/element.py", line 1231, in __str__
        return 'Element({})'.format(self.vertices)
      File "/home/eivind/repos/nutils/nutils/element.py", line 1193, in vertices
        return transform.apply(self.transform, self.reference.vertices)
      File "/home/eivind/repos/nutils/nutils/transform.py", line 33, in apply
        points = trans.apply(points)
    AttributeError: 'Identifier' object has no attribute 'apply'

**Comment by gertjanvanzwieten** [comment]
Thanks, I'll look into this.
